spring:
  ## h2数据库配置
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  ## 数据源配置
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:dev
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8